services:
    php:
        container_name: nicuSymfonyPhp
        build:
            context: ./docker/php
        volumes:
            - ./app:/var/www/html
        networks:
            - symfony
    nginx:
        container_name: nicuSymfonyNginx
        build:
            context: ./docker/nginx
        ports:
            - "9500:80"
        volumes:
            - ./app:/var/www/html
        networks:
            - symfony
    db:
        container_name: nicuSymfonyDatabase
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '4306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - symfony
volumes:
    mysql:

networks:
    symfony: